### ISSUE TITLE
Crear un crud básico para evaluación proveedores

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_crud#1]
según el modelo de datos de la evaluación de proveedores, el cual se encuentran en la carpeta de Agora compartida al equipo, realizar:

- [x] montar la base de datos en local

- [x] crud basico basado en el modelo de base de datos 

- [x] subir el api al repo. 

- [x] realizar el readme respectivo para el api, este debe incluir entre sus componentes, como adicion la imagen del modelo de datos.

**Comment by grumysh** [comment]
Todo OK!!!
