### ISSUE TITLE
gestión para despliegue de evaluaciones_crud en test

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_crud#11]
se requiere 
- [x] registro de variables en parameter store 
- [x] registro de variables de entorno para amazon

- [x]  archivos de integración continua 

- [x] resolución de problemas de compilación y despliegue 

- [x] registro de api en wso2 en test

- [x] validación de funcionamiento base

**Comment by BOTOOM** [comment]
https://tuleap.udistrital.edu.co/plugins/tracker/?aid=34267

**Comment by Eduargonzalez** [comment]
De igual manera informar al ingeniero para el respectivo tramite de la solicitud.

**Comment by BOTOOM** [comment]
api ya desplegada , hace falta su registro en wso2
