### ISSUE TITLE
Refactor crud evaluación y verificación de pk auto

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_crud#2]
el api debe de ceñirse a los lineamientos de la oficina y debe de responder sus datos y errores en json adicionalmente los datos nuevos deben de generar el id automáticamente para ello:

- [x] realizar refactor al api. 

- [x] verificar en los modelos de cada tabla que el id tenga el "pk auto". 

- [x] si el modelo no cumple con el item anterior añadir la funcionalidad

**Comment by grumysh** [comment]
Todo se realiza ok!!
