### ISSUE TITLE
adición de la librería time_bogota para las fechas automáticas

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_crud#3]
con el fin de hacer cumplimiento a los lineamientos, l para los daytos de `fecha_creacion` y `fecha modificacion`, se deben de generar automáticamente, para ello se utilizara una libreria de la organización ; `time_bogota` ; con el fin de que las fechas sean generadas al momento de realizar la petición.

dicha librería deberá ser implementada en POST y  PUT de cada controlador

**Comment by grumysh** [comment]
Todo ok!!
