### ISSUE TITLE
Realizar beego migrations

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/evaluacion_crud#4]
en cumplimiento de los lineamientos. Para el ambiente de test es necesario que la base de datos no se cree manualmente, para ello se debe utilizar beego migration en el cual se le dará un usuario con los debidos permisos, al api el cual creara el modelo e ingresara los datos necesarios.

**Comment by BrayanB24** [comment]
Se inicia el desarrollo

**Comment by BrayanB24** [comment]
Se termina el desarrollo de las migraciones y se comprueba que estas funcionan de manera correcta. El script para ejecutarlas en local es el siguiente:
`bee migrate -driver=postgres -conn="postgres://postgres:12345678@127.0.0.1:5432/evaluacion_proveedores?sslmode=disable&search_path=public"`

**Comment by BrayanB24** [comment]
Se ajustan las migraciones para que funcionen de maera correcta con el usuario de test, ademas de añadir las variables de entorno y los archivos necesarios para el CI. Se da por terminada la tarea.
